import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // let fruits = [
  //   ["olma", "anor"],
  //   [["olma", "anor"], ["salom"]],
  //   ["olcha", "gilos"],
  // ];
  // function Task1(arr: (string[] | string[][])[]) {
  //   return arr.flat(Infinity);
  // }

  // function Calc(arr: number[]) {
  //   // let res = arr.map((item, index, array) => item)

  //   for (let i = 0; i < arr.length; i++) {
  //     for (let y = 0; y < arr.length; y++) {
  //       for (let t = 0; t < arr.length; t++) {
  //         if (arr[i] + arr[y] == arr[t]) {
  //           console.log(arr[i], arr[y]);
  //         }
  //       }
  //     }
  //   }
  // }
  // Calc([4, 9, 2, 6, 10]);

  let hotels = [
    {
      title: "Nurjahon-Hotel",
      roomPrices: {
        1: "50$",
        2: "200$",
        3: "300$",
      },
    },
    {
      title: "Nurjahon-Hotel",
      roomPrices: {
        1: "50$",
        2: "200$",
        3: "300$",
      },
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      </main>
    </>
  );
}
